# 可以 x86-64 架构上使用 qemu-user-static 模拟 riscv64 架构

# node 对 riscv64 平台的官方支持还不完善，故采用 amd64 架构编译前端，再复制到 riscv64 架构的 nginx 镜像中
FROM --platform=linux/amd64 node:22 AS build-frontend
WORKDIR /app
RUN apt-get update && apt-get install -y git
RUN git clone https://gitee.com/xfan1024/spring-petclinic-angular.git .
RUN npm install && npm run build -- --output-path=./dist/out --configuration production

# 前端容器使用 nginx 镜像
FROM --platform=linux/riscv64 xfan1024/openeuler:24.03-riscv64
RUN dnf install -y nginx && dnf clean all && rm -rf /usr/share/nginx/html
COPY --from=build-frontend /app/dist/out /usr/share/nginx/html
COPY spa.conf /etc/nginx/default.d/spa.conf 
CMD ["nginx", "-g", "daemon off; error_log /dev/stderr info;"]
EXPOSE 80
